services:
    xtain_filter_query_builder.expression.default_expression_factory:
        class: XTAIN\FilterQueryBuilder\Expr\DefaultExpressionFactory

    xtain_filter_query_builder.expression.default_conjunction_factory:
        class: XTAIN\FilterQueryBuilder\Expr\DefaultConjunctionFactory

    xtain_filter_query_builder.builder_factory:
        class: XTAIN\FilterQueryBuilder\BuilderFactory
        arguments:
            - [ "@xtain_filter_query_builder.expression.default_expression_factory" ]
            - [ "@xtain_filter_query_builder.expression.default_conjunction_factory" ]