services:
    xtain_filter_query_builder.builder_factory:
        class: XTAIN\FilterQueryBuilder\BuilderFactory
        arguments:
            -
               - XTAIN\FilterQueryBuilder\Expr\BetweenExpression
               - XTAIN\FilterQueryBuilder\Expr\EqualExpression
               - XTAIN\FilterQueryBuilder\Expr\LessGreaterExpression
               - XTAIN\FilterQueryBuilder\Expr\NullExpression
            -
               - XTAIN\FilterQueryBuilder\Expr\AndxConjunction
               - XTAIN\FilterQueryBuilder\Expr\OrxConjunction
